# Generated by Django 4.1.4 on 2023-01-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0002_20230112_add_blogger_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="author",
            name="is_deleted",
        ),
    ]
