version: '3.2'
services:
    web:
      build:
        context: ..
        dockerfile: docker/Dockerfile

      expose:
        - 8000

      depends_on:
        - db
        - redis


    db:
      image: postgres:15-alpine

      volumes:
        - postgres_data:/var/lib/postgresql/data

      environment:
        POSTGRES_PASSWORD: blog

      expose:
        - 5432


    redis:
      image: redis:7-alpine

      expose:
        - 6379


volumes:
  postgres_data: {}
