version: '3.2'
services:
    web:
      build:
        context: ..
        dockerfile: docker/Dockerfile

      expose:
        - 8000


    db:
      image: postgres:15-alpine

      volumes:
        - postgres_data:/var/lib/postgresql/data

      environment:
        POSTGRES_PASSWORD: blog

      expose:
        - 5432


volumes:
  postgres_data: {}
